apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandrasvc
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    interface: cassandrasvc
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: cassandra
  namespace: default
spec:
  serviceName: cassandrasvc
  replicas: 3
  template:
    metadata:
      labels:
        app: cassandra
        interface: cassandrasvc
      namespace: default
    spec:
      containers:
        - name: cassandra
          image: cassandra
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_SEEDS
              value: cassandra-0.cassandrasvc.default.svc.c7secure.com
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra/data
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
        annotations:  # comment line if you want to use a StorageClass
          volume.beta.kubernetes.io/storage-class: glusterfs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi